# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    session:
        handler_id: '%env(REDIS_URL)%'
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native


    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
